nome=str(input('Digite o seu nome completo: ')).strip()
print('Seu nome em maiúscula é {}'.format(nome.upper()))
print('Seu nome em minúsculas é {}'.format(nome.lower()))
print('Seu nome tem ao todo {} letras'.format(len(nome) - nome.count(' ')))
dividido=nome.split()
print('Seu Primeiro nome tem {}'.format(len(dividido[0])))